server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/student?serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: rong195302
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false #关闭缓存
    #prefix: classpath:/templates/
  mvc:
    static-path-pattern: /1.jpg
  resources:
    static-locations:  file:F:\project\Springboot-Mybatis-CRUD-master\mybatis-demo1\src\main\resources\static

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

